/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ulatina.grupo5.vista;

/**
 *
 * @author josep
 */
public class Menu_Admin extends javax.swing.JFrame {

    /**
     * Creates new form MainAdmin
     */
    public Menu_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Menu_Admin = new javax.swing.JPanel();
        jLabel_Registrar_Usuarios_Main_admin = new javax.swing.JLabel();
        jButton_Registrar_Usuarios_Main_admin = new javax.swing.JButton();
        jButton_add_atraccion_main_admin = new javax.swing.JButton();
        jLabel_Registrar_atrac_Main_admin = new javax.swing.JLabel();
        jButton_mantenimiento_atracciones_main_admin = new javax.swing.JButton();
        jButton_ganancias_main_menu = new javax.swing.JButton();
        jButton5_back_main_menu_admin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Ver_Usuarios_Main_Admin = new javax.swing.JButton();
        jButton_Buscar_Atraccio_Main_Admin = new javax.swing.JButton();
        jLabel_Ver_Usuarios_Main_admin = new javax.swing.JLabel();
        jLabel_Buscar_Atracciones_Main_Admin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_menu_admin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Registrar_Usuarios_Main_admin.setText("Registrar Usuarios");

        jButton_Registrar_Usuarios_Main_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/add-user.png"))); // NOI18N
        jButton_Registrar_Usuarios_Main_admin.setContentAreaFilled(false);

        jButton_add_atraccion_main_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/add-attraction.png"))); // NOI18N
        jButton_add_atraccion_main_admin.setContentAreaFilled(false);

        jLabel_Registrar_atrac_Main_admin.setText("Agregar Atracción");

        jButton_mantenimiento_atracciones_main_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/mantenimiento atra.png"))); // NOI18N
        jButton_mantenimiento_atracciones_main_admin.setContentAreaFilled(false);

        jButton_ganancias_main_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/money.png"))); // NOI18N
        jButton_ganancias_main_menu.setContentAreaFilled(false);

        jButton5_back_main_menu_admin.setContentAreaFilled(false);

        jLabel1.setText("Seguimiento de Atracciones");

        jLabel2.setText("Ganancias");

        jButton_Ver_Usuarios_Main_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/buscar_user.png"))); // NOI18N
        jButton_Ver_Usuarios_Main_Admin.setContentAreaFilled(false);

        jButton_Buscar_Atraccio_Main_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/parque-de-atracciones.png"))); // NOI18N
        jButton_Buscar_Atraccio_Main_Admin.setContentAreaFilled(false);

        jLabel_Ver_Usuarios_Main_admin.setText("Ver Usuarios");

        jLabel_Buscar_Atracciones_Main_Admin.setText("Buscar Atracciones");

        javax.swing.GroupLayout jPanel_Menu_AdminLayout = new javax.swing.GroupLayout(jPanel_Menu_Admin);
        jPanel_Menu_Admin.setLayout(jPanel_Menu_AdminLayout);
        jPanel_Menu_AdminLayout.setHorizontalGroup(
            jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton5_back_main_menu_admin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Menu_AdminLayout.createSequentialGroup()
                .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Registrar_Usuarios_Main_admin)
                            .addComponent(jLabel_Registrar_Usuarios_Main_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Buscar_Atraccio_Main_Admin)))
                    .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel_Buscar_Atracciones_Main_Admin)))
                .addGap(90, 90, 90)
                .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                        .addComponent(jLabel_Ver_Usuarios_Main_admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Registrar_atrac_Main_admin))
                    .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                        .addComponent(jButton_mantenimiento_atracciones_main_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ganancias_main_menu))
                    .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                        .addComponent(jButton_Ver_Usuarios_Main_Admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_add_atraccion_main_admin))
                    .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );
        jPanel_Menu_AdminLayout.setVerticalGroup(
            jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_Registrar_Usuarios_Main_admin)
                        .addComponent(jButton_Ver_Usuarios_Main_Admin, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton_add_atraccion_main_admin))
                .addGap(45, 45, 45)
                .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Registrar_atrac_Main_admin)
                    .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Registrar_Usuarios_Main_admin)
                        .addComponent(jLabel_Ver_Usuarios_Main_admin)))
                .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_mantenimiento_atracciones_main_admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_ganancias_main_menu, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel_Menu_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_Menu_AdminLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Buscar_Atraccio_Main_Admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Buscar_Atracciones_Main_Admin)
                        .addGap(18, 18, 18)))
                .addComponent(jButton5_back_main_menu_admin)
                .addGap(45, 45, 45))
        );

        jLabel_menu_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/menu_admin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel_menu_admin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_menu_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Menu_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Menu_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton5_back_main_menu_admin;
    public javax.swing.JButton jButton_Buscar_Atraccio_Main_Admin;
    public javax.swing.JButton jButton_Registrar_Usuarios_Main_admin;
    public javax.swing.JButton jButton_Ver_Usuarios_Main_Admin;
    public javax.swing.JButton jButton_add_atraccion_main_admin;
    public javax.swing.JButton jButton_ganancias_main_menu;
    public javax.swing.JButton jButton_mantenimiento_atracciones_main_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Buscar_Atracciones_Main_Admin;
    private javax.swing.JLabel jLabel_Registrar_Usuarios_Main_admin;
    private javax.swing.JLabel jLabel_Registrar_atrac_Main_admin;
    private javax.swing.JLabel jLabel_Ver_Usuarios_Main_admin;
    private javax.swing.JLabel jLabel_menu_admin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Menu_Admin;
    // End of variables declaration//GEN-END:variables
}
