/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ulatina.grupo5.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class Registro_Usuarios_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro_Usuarios_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_type_of_user = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1_Regist_Users_Admin = new javax.swing.JPanel();
        jLabelCedula = new javax.swing.JLabel();
        jLabel_contra = new javax.swing.JLabel();
        jLabel_correo = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_Primer_apellido = new javax.swing.JLabel();
        jLabel_Segundo_Apellido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_create_user = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();
        ddlTipoUser = new javax.swing.JComboBox<>();
        txtCed = new javax.swing.JTextField();
        txtSegundoApe = new javax.swing.JTextField();
        txtPrimerApe = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jButton_previous_register = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel_contra1 = new javax.swing.JLabel();
        dtpFechaCumpleanos = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_registro_user = new javax.swing.JLabel();

        jComboBox_type_of_user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Admin", "2- Empleado", "3- Cliente" }));
        jComboBox_type_of_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_type_of_userActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCedula.setText("Cédula");

        jLabel_contra.setText("Contraseña");

        jLabel_correo.setText("Correo");

        jLabel_nombre.setText("Nombre");

        jLabel_Primer_apellido.setText("Primer Apellido");

        jLabel_Segundo_Apellido.setText("Segundo Apellido");

        jLabel7.setText("Tipo de Usuario");

        jButton_create_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/sign up.png"))); // NOI18N
        jButton_create_user.setContentAreaFilled(false);

        txtContra.setText("**********************************");

        ddlTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Admin", "2- Empleado", "3- Cliente" }));

        jButton_previous_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/previous1.png"))); // NOI18N
        jButton_previous_register.setContentAreaFilled(false);

        btnActualizar.setText("Actualizar");

        jLabel_contra1.setText("Fecha Cumpleaños:");

        javax.swing.GroupLayout jPanel1_Regist_Users_AdminLayout = new javax.swing.GroupLayout(jPanel1_Regist_Users_Admin);
        jPanel1_Regist_Users_Admin.setLayout(jPanel1_Regist_Users_AdminLayout);
        jPanel1_Regist_Users_AdminLayout.setHorizontalGroup(
            jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(93, 93, 93)
                                .addComponent(ddlTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_contra)
                                    .addComponent(jLabel_correo)
                                    .addComponent(jLabelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Segundo_Apellido)
                                    .addComponent(jLabel_Primer_apellido)
                                    .addComponent(jLabel_nombre)
                                    .addComponent(jLabel_contra1))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtContra)
                                    .addComponent(txtCorreo)
                                    .addComponent(txtCed)
                                    .addComponent(txtSegundoApe)
                                    .addComponent(txtPrimerApe)
                                    .addComponent(txtNombre)
                                    .addComponent(dtpFechaCumpleanos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton_previous_register)
                        .addGap(75, 75, 75)
                        .addComponent(jButton_create_user, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_Regist_Users_AdminLayout.setVerticalGroup(
            jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Primer_apellido)
                    .addComponent(txtPrimerApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Segundo_Apellido)
                    .addComponent(txtSegundoApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula)
                    .addComponent(txtCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_correo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_contra)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_contra1)
                    .addComponent(dtpFechaCumpleanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ddlTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                        .addGroup(jPanel1_Regist_Users_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jButton_previous_register))
                            .addGroup(jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton_create_user, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_Regist_Users_AdminLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        jLabel_registro_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/registrouser1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel_registro_user)
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_registro_user, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1_Regist_Users_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1_Regist_Users_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_type_of_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_type_of_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_type_of_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuarios_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuarios_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuarios_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Usuarios_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Usuarios_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JComboBox<String> ddlTipoUser;
    public com.toedter.calendar.JDateChooser dtpFechaCumpleanos;
    public javax.swing.JButton jButton_create_user;
    public javax.swing.JButton jButton_previous_register;
    public javax.swing.JComboBox<String> jComboBox_type_of_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabel_Primer_apellido;
    private javax.swing.JLabel jLabel_Segundo_Apellido;
    public javax.swing.JLabel jLabel_contra;
    public javax.swing.JLabel jLabel_contra1;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_registro_user;
    private javax.swing.JPanel jPanel1_Regist_Users_Admin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField txtCed;
    public javax.swing.JPasswordField txtContra;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrimerApe;
    public javax.swing.JTextField txtSegundoApe;
    // End of variables declaration//GEN-END:variables
}
